name: Check external links

on:
  pull_request:

  push:
    branches:
      - 'feature/**'
      - 'v[0-9]'

  workflow_dispatch:

jobs:
  check-links:
    name: Check for broken external links
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Install dependencies
        uses: ./.github/workflows/actions/install-node

      - name: Build
        uses: ./.github/workflows/actions/build

      - name: Check external broken links
        id: check-links
        run: npm run check-external-links
