name: Test

on:
  pull_request:

  push:
    branches:
      - 'feature/**'
      - 'v[0-9]'

  workflow_dispatch:
    inputs:
      runner:
        description: Run tests on
        type: choice
        default: ubuntu-latest
        options:
          - macos-latest
          - ubuntu-latest
          - windows-latest

jobs:
  build:
    name: Build
    runs-on: ${{ github.event.inputs.runner || 'ubuntu-latest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        uses: ./.github/workflows/actions/install-node

      - name: Build website
        uses: ./.github/workflows/actions/build

  test:
    name: ${{ matrix.task.description }}
    runs-on: ${{ github.event.inputs.runner || 'ubuntu-latest' }}
    needs: [build]

    strategy:
      fail-fast: false

      matrix:
        task:
          - description: Lint Sass
            run: npm run lint:scss

          - description: Lint JavaScript
            run: npm run lint:js

          - description: Lint HTML
            run: npm run lint:html --ignore-scripts

          - description: EditorConfig
            run: npm run lint:editorconfig

          - description: Prettier
            run: npm run lint:prettier

          - description: TypeScript compiler
            run: npm run lint:types -- --pretty

          - description: JavaScript tests
            run: npx jest --color --maxWorkers=2

          - description: Check broken links
            run: npm run check-links

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install dependencies
        uses: ./.github/workflows/actions/install-node

      - name: Build
        uses: ./.github/workflows/actions/build

      - name: Run task
        id: task
        run: ${{ matrix.task.run }}
        continue-on-error: ${{ matrix.task.continue-on-error || false }}

      - name: Task warnings
        if: steps.task.outcome == 'failure'
        run: echo "::warning title=${{ matrix.task.description }} task failed::Check has been temporarily ignored"
